### PR TITLE
Fix OTP compatibility

### LINKED ISSUE #932: Failing 1.0.0 with Elixir 1.11.4 / OTP 24.1.7
On using `erlef/setup-beam` combinations of Elixir <= 1.11 and OTP 24 are failing with the new 1.0.0 release.

```
Error: 5.042 [error] Task #PID<0.162.0> started from :hex_fetcher terminating
Warning: ** (UndefinedFunctionError) function :ssl.cipher_suites/1 is undefined or private
    (ssl 10.5.3) :ssl.cipher_suites(:openssl)
    (hex 1.0.0) lib/hex/http/ssl.ex:123: Hex.HTTP.SSL.filter_ciphers/1
```

### PR DESCRIPTION
**Pull request by ericmj**
Closes #932.

### CODE REVIEW

File: lib/hex/stdlib.ex [hunk 1]
```diff
@@ -117,53 +117,57 @@ defmodule Hex.Stdlib do
   end
 
   # TODO: Remove this once we require OTP 22.1
-  if Code.ensure_loaded?(:crypto) and function_exported?(:crypto, :mac, 4) do
-    def crypto_hmac(type, key, data), do: :crypto.mac(:hmac, type, key, data)
-  else
-    def crypto_hmac(type, key, data), do: :crypto.hmac(type, key, data)
+  def crypto_hmac(type, key, data) do
+    if Code.ensure_loaded?(:crypto) and function_exported?(:crypto, :mac, 4) do
+      apply(:crypto, :mac, [:hmac, type, key, data])
```
Comment (wojtekmach) [inline lib/hex/stdlib.ex:122]: wdyt about using the new API without apply, i.e.:

```suggestion
      :crypto.mac(:hmac, type, key, data)
```

I believe this should compile on old OTPs, just emit a compile-time warning, right?

but totally fine as is!

**Review by wojtekmach — APPROVED** [review]

File: lib/hex/stdlib.ex (hunk 1 above)
Comment (ericmj) [reply lib/hex/stdlib.ex:122]: Yes, it will compile but may emit a warning on some versions. I want to reduce the amount of irrelevant warnings so the relevant ones don't get lost in the noise.

**Comment by cw789** [comment]
Thanks a lot Eric.

File: lib/hex/stdlib.ex (hunk 1 above)
Comment (wojtekmach) [reply lib/hex/stdlib.ex:122]: good call!
