### PR TITLE
Fix building requests from umbrella apps

### LINKED ISSUE #997: Installing github dependencies broken on main
# Versions
## elixir
Erlang/OTP 25 [erts-13.2.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]

Elixir 1.14.5 (compiled with Erlang/OTP 25)

## hex
main@15f9e6605295b61ce8ffe8e64501afc09afac622

# To reproduce
```
Mix.install([{:elixir_ls, github: "elixir-lsp/elixir-ls", tag: "v0.14.6"}])
```
# Result
```
* Getting elixir_ls (https://github.com/elixir-lsp/elixir-ls.git - v0.14.6)
remote: Enumerating objects: 10404, done.        
remote: Counting objects: 100% (10404/10404), done.        
remote: Compressing objects: 100% (3633/3633), done.        
remote: Total 10404 (delta 6692), reused 10055 (delta 6501), pack-reused 0        
* Getting elixir_sense (https://github.com/elixir-lsp/elixir_sense.git - 71efd1e2efbac43e6c98c525cc879ddd747ac62e)
remote: Enumerating objects: 10083, done.        
remote: Counting objects: 100% (1605/1605), done.        
remote: Compressing objects: 100% (577/577), done.        
remote: Total 10083 (delta 1161), reused 1280 (delta 1017), pack-reused 8478        
* Getting erl2ex (https://github.com/dazuma/erl2ex.git)
remote: Enumerating objects: 1431, done.        
remote: Total 1431 (delta 0), reused 0 (delta 0), pack-reused 1431        
origin/HEAD set to master
* Getting dialyxir_vendored (https://github.com/elixir-lsp/dialyxir.git - 896fa45817c6a1be8ec408577c88ab52c27f6851)
remote: Enumerating objects: 3198, done.        
remote: Counting objects: 100% (386/386), done.        
remote: Compressing objects: 100% (179/179), done.        
remote: Total 3198 (delta 181), reused 359 (delta 169), pack-reused 2812        
* Getting jason_v (https://github.com/elixir-lsp/jason.git - c81537e2a5e1acacb915cf339fe400357e3c2aaa)
remote: Enumerating objects: 1553, done.        
remote: Counting objects: 100% (229/229), done.        
remote: Compressing objects: 100% (87/87), done.        
remote: Total 1553 (delta 160), reused 148 (delta 142), pack-reused 1324        
* Getting path_glob_vendored (https://github.com/elixir-lsp/path_glob.git - origin/vendored)
remote: Enumerating objects: 395, done.        
remote: Counting objects: 100% (395/395), done.        
remote: Compressing objects: 100% (200/200), done.        
remote: Total 395 (delta 179), reused 361 (delta 149), pack-reused 0        
* Getting mix_task_archive_deps (https://github.com/elixir-lsp/mix_task_archive_deps.git)
remote: Enumerating objects: 265, done.        
remote: Counting objects: 100% (57/57), done.        
remote: Compressing objects: 100% (27/27), done.        
remote: Total 265 (delta 20), reused 57 (delta 20), pack-reused 208        
origin/HEAD set to master
Failed to fetch record for elixir_ls_utils from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
Failed to fetch record for elixir_ls_debugger from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
Failed to fetch record for elixir_ls from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
** (Mix.Error) No package with name elixir_ls (from: mix.exs) in registry
    (mix 1.14.5) lib/mix.ex:513: Mix.raise/2
    (hex 2.0.7-dev) lib/hex/remote_converger.ex:319: Hex.RemoteConverger.verify_package_req/4
    (elixir 1.14.5) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (hex 2.0.7-dev) lib/hex/remote_converger.ex:304: Hex.RemoteConverger.verify_input/2
    (hex 2.0.7-dev) lib/hex/remote_converger.ex:51: Hex.RemoteConverger.converge/2
    (mix 1.14.5) lib/mix/dep/converger.ex:118: Mix.Dep.Converger.all/4
    (mix 1.14.5) lib/mix/dep/converger.ex:74: Mix.Dep.Converger.converge/4
    iex:1: (file)
iex(1)> Failed to fetch record for jason_v from registry (using cache instead)
This could be because the package does not exist, it was spelled incorrectly or you don't have permissions to it
```

### PR DESCRIPTION
**Pull request by ericmj**
Closes #997.

### CODE REVIEW

File: lib/hex/mix.ex [hunk 1]
```diff
@@ -68,6 +58,34 @@ defmodule Hex.Mix do
...
+            }
+          ]
+        else
+          []
+        end
+      else
+        []
+      end
+    end)
+  end
```
Comment (supersimple) [inline lib/hex/mix.ex:87]:
```suggestion
  defp non_hex_deps_to_requests(deps, all_deps, all_apps, overridden) do
    Enum.flat_map(deps, fn dep ->
      if has_non_hex_deps?(dep, all_apps) do
        collect_non_hex_deps(deps, all_deps, all_apps, overridden)
      else
        []
      end
    end)
  end

  defp has_non_hex_deps?(dep, all_apps) do
    dep.scm != Hex.SCM and dep.deps != [] and dep.app in all_apps
  end

  defp collect_non_hex_deps(deps, all_deps, all_apps, overridden) do
    sub_apps = Enum.map(dep.deps, & &1.app)
    sub_deps = Enum.filter(dep.deps, &(&1.app in sub_apps))

    dependencies = deps_to_requests(sub_deps, all_deps, all_apps, overridden)

    if dependencies != [] do
      [
        %{
          repo: nil,
          name: Atom.to_string(dep.app),
          requirement: nil,
          app: Atom.to_string(dep.app),
          from: Path.relative_to_cwd(dep.from),
          dependencies: dependencies
        }
      ]
    else
      []
    end
  end
```

Comment (supersimple) [reply lib/hex/mix.ex:87]: This just looks a little Java-like.
Any thoughts on breaking up that nested if/else into something more descriptive?

**Review by supersimple — APPROVED** [review]

File: lib/hex/mix.ex (hunk 1 above)
Comment (ericmj) [reply lib/hex/mix.ex:87]: This looks way better. Thanks!

**Review by lukaszsamson — APPROVED** [review]
