### PR TITLE
Mention overrides and pre-releases in resolver error

### LINKED ISSUE #232: Doesn't know how to compare x.x.x-rc
When attempting to use `ja_serializer` and the `ecto` release candidate I ran into the following error:

```
Failed to use "ecto" because
  ja_serializer (version 0.9.0) requires > 1.0.0
  Locked to 2.0.0-rc.5 in your mix.lock

** (Mix) Hex dependency resolution failed, relax the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock)
```

Here is the output of `mix hex.info` for debug purposes:

```
mix hex.info  
Hex:    0.12.0
Elixir: 1.2.5
OTP:    18.3

Built with: Elixir 1.2.5 and OTP 18.3.3
```

My short term fix for this has simply been to override the version of ecto I'm using:

    {:ecto, "2.0.0-rc.5", override: true},

### PR DESCRIPTION
**Pull request by ericmj**
Closes #232.

/cc @josevalim

### CODE REVIEW

File: lib/hex/remote_converger.ex [hunk 1]
```diff
@@ -41,15 +41,22 @@ defmodule Hex.RemoteConverger do
...
 
+  defp resolver_failed(message) do
+    Hex.Shell.info "\n" <> message
+
+    Mix.raise "Hex dependency resolution failed, relax the version " <>
+              "requirements of your dependencies or unlock them (by " <>
+              "using mix deps.update or mix deps.unlock). If you are " <>
+              "unable to resolve the conflicts you can try overriding " <>
+              "with {:dependency, \"~> 1.0\", override: true}"
+  end
```
Comment (ericmj) [inline lib/hex/remote_converger.ex]: New error message mentioning overrides.

File: lib/hex/resolver.ex [hunk 2]
```diff
@@ -208,6 +208,18 @@ defmodule Hex.Resolver do
...
+  defp pre_message(message) do
+    # ugly hack to check if we should print the pre-release explanation
+    if :binary.match(message, "*\n") == :nomatch do
+      message
+    else
+      message <>
+        "\n* This requirement failed because by default pre-releases " <>
+        "are never matched. To match against pre-releases include " <>
+        "a pre-release in the requirement string: \"~> 2.0-beta\".\n"
+    end
```
Comment (ericmj) [inline lib/hex/resolver.ex]: Message mentioning pre-releases. A requirement that didn't match because of the pre-release behavior will have `*` appended to it.

File: lib/hex/resolver.ex [hunk 3]
```diff
@@ -208,6 +208,18 @@ defmodule Hex.Resolver do
     |> Enum.map(&Backtracks.message/1)
     |> Enum.reject(&is_nil/1)
     |> Enum.join("\n\n")
-    |> Kernel.<>("\n")
+    |> pre_message
+  end
+
+  defp pre_message(message) do
+    # ugly hack to check if we should print the pre-release explanation
+    if :binary.match(message, "*\n") == :nomatch do
```
Comment (josevalim) [inline lib/hex/resolver.ex]: `message =~ "*\n"`

**Comment by josevalim** [comment]
@ericmj :shipit:!

What about a special error message if all the package published so far are pre-releases as @mobileoverlord mentioned?

**Comment by ericmj** [comment]
> What about a special error message if all the package published so far are pre-releases as @mobileoverlord mentioned?

That's a good point but then we could potentially have two similar messages to show users at the same time. I think it can start to feel like a wall of text that users will just skip reading.

What was the use case @mobileoverlord?

**Comment by josevalim** [comment]
@ericmj he is just going to publish pre-releases because he needs the `-ddd` to add more information.

File: lib/hex/resolver.ex (hunk 3 above)
Comment (ericmj) [inline lib/hex/resolver.ex]: Right, I forgot about the operator. I was initially surprised that `String.match?/2` didn't have the `:binary` optimization, should we add that?

**Comment by ericmj** [comment]
I think this is message is good enough for that. Lets see what the feedback says.
